[build-system]
requires = [
    "setuptools",
    "wheel",
    "toml",
    "versioningit"
]
build-backend = "setuptools.build_meta"

[project]
name = "mlx"
authors = [
    {name = "Jacob Hauck", email = "jacobh15@yahoo.com"}
]
description = "Basic tools for creating machine learning experiments"
readme = "README.md"
license = "MIT"
classifiers = [
    "Programming Language :: Python :: 3"
]
dependencies = [
    "wandb",
    "PyYAML",
    'importlib-metadata; python_version>="3.11"'
]
dynamic = ["version"]

[tool.versioningit.vcs]
method = "git"
match = ["v*"]
default-tag = "0.0.1"

[tool.versioningit.next-version]
method = "minor"

[tool.versioningit.format]
distance = "{next_version}"
dirty = "{next_version}"
distance-dirty = "{next_version}"

[tool.versioningit.write]
file = "mlx/_version.py"

[tool.setuptools.packages.find]
exclude = ["experiments*"]
