[build-system]
requires = [
    "setuptools",
    "wheel",
    "toml"
]
build-backend = "setuptools.build_meta"

[project]
name = "mlx"
authors = [{name = "Jacob Hauck", email = "jacobh15@yahoo.com"}]
description = "Basic tools for creating machine learning experiments"
version = "1.0.0"
readme = "README.md"
license = "MIT"
classifiers = [
    "Programming Language :: Python :: 3"
]
dependencies = [
    "wandb",
    "PyYAML",
    'importlib-metadata; python_version>="3.11"'
]

[project.scripts]
mlx = "mlx.run:_run_cli"

[tool.setuptools.packages.find]
exclude = ["experiments*"]
